/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Animated from "../components/Animated";
import Game from "../components/Game";
import Space from "../components/Space";
import Users from "../components/Users";
import Box from "../components/Box";
import Block from "../components/Block";
import Link from "next/link";
import Colour from "../components/Colour";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import Credential from "../components/Credential";
import styles from "../styles/index.module.scss";
import Boost from "../components/Boost";
import Game1 from "../components/Game1";
import Homepage from "../components/Homepage";
import Door from "../components/Door";

export default function Home() {
  // const [offsety, setOffsety] = useState(0);
  // const handleScroll = () => setOffsety(window.pageYOffset);

  useEffect(() => {
    const parallax = document.getElementById("first");
    window.addEventListener("scroll", function () {
      let offset = window.pageYOffset;
      parallax.style.backgroundPositionY = offset * 0.7 + "px";
    });
  }, []);

  const [ulist, setUlist] = useState([]);

  const count = useSelector((state) => state.colour.value);
  const info = useSelector((state) => state.colour.info);
  const status = useSelector((state) => state.colour.login);

  // useEffect(() => {
  //   console.log("in index",ulist);
  // },[ulist]);

  const router = useRouter();

  function sendColour() {
    console.log(info.colour);
    router.push({
      pathname: "/test",
      query: {
        colour: info.colour,
        id: info._id,
      },
    });
  }

  return (
    <>
      <Head>
        <title>ZoneX</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="div1" id="first">
        {/* <Boost props={count} />
        <h1 className="sth1">
          <span className="Head f4"> Zone X </span>
        </h1> */}
        <Homepage count={count} />
      </div>

      {/* <Game /> */}
      <Game1 />

      <div className="div1">
        <Users setUlist={setUlist} />
      </div>

      <div className="div1">
        <h1 className="sth1">
          {status && (
            <a
              onClick={sendColour}
              style={{ cursor: "pointer", textDecoration: "none" }}
            >
              {" "}
              <span className="Head f6">YOUR NAME </span>
            </a>
          )}

          {!status && (
            <Link href="/test">
              <a style={{ textDecoration: "none" }}>
                {" "}
                <span className="Head f6"> NAME </span>
              </a>
            </Link>
          )}
        </h1>
      </div>

      {/* <div className="div1" style={{ position: "relative" }}>
       <Block />
      </div> */}
{/* 
      <div className="div1 door">
        <h1 className="sth1">
          <Link href="/space">
            <a style={{ textDecoration: "none" }}>
              {" "}
              <span className="Head f7"> PLAYGROUND </span>
            </a>
          </Link>
        </h1>
      </div> */}
      <Door/>

      <div>
        <Colour ulist={ulist} setUlist={setUlist} />
      </div>
    </>
  );
}
